/** Stable package identity for diagnostics and boundary tests. */
export const SDK_PACKAGE_NAME = '@kyxos/render-sdk' as const;

export type {
  BackendBindGroupDescriptor,
  BackendBindGroupHandle,
  BackendBufferData,
  BackendBufferDescriptor,
  BackendBufferHandle,
  BackendCapabilityReport,
  BackendClearColor,
  BackendCommandEncoderDescriptor,
  BackendCommandEncoderHandle,
  BackendDrawCommand,
  BackendEvents,
  BackendFrameSubmission,
  BackendLifecycleState,
  BackendLossInfo,
  BackendPipelineHandle,
  BackendRenderPipelineDescriptor,
  BackendRenderPassDescriptor,
  BackendRenderPassStatistics,
  BackendResourceDescriptor,
  BackendResourceHandle,
  BackendResourceKind,
  BackendResourceStatistics,
  BackendSamplerDescriptor,
  BackendSamplerHandle,
  BackendShaderCompilationInfo,
  BackendShaderModuleDescriptor,
  BackendShaderModuleHandle,
  BackendSurfaceDescriptor,
  BackendSurfaceHandle,
  BackendSurfaceInfo,
  BackendSurfaceResize,
  BackendSurfaceSize,
  BackendSurfaceTarget,
  BackendTextureDescriptor,
  BackendTextureHandle,
  BackendType,
  GraphicsBackend,
} from '@kyxos/render-backend-api';
export { BACKEND_RESOURCE_KINDS, createBackendCapabilityReport } from '@kyxos/render-backend-api';
export type { DirtyFlag, FrameRequestDriver, RenderMode } from '@kyxos/render-frame-scheduler';
export {
  OrbitController,
  PerspectiveCamera,
  frameScene,
  type CameraChangeEvent,
  type CameraChangeKind,
  type CameraDiagnostics,
  type CameraEvents,
  type CameraFitOptions,
  type CameraFitResult,
  type CameraPerspectiveOptions,
  type CameraPoseOptions,
  type FrameSceneOptions,
  type OrbitControllerOptions,
  type OrbitState,
  type PerspectiveCameraOptions,
} from '@kyxos/render-camera';
export {
  createCubeGeometry,
  createMeshData,
  createPlaneGeometry,
  createUvSphereGeometry,
  type CubeGeometryOptions,
  type MeshData,
  type MeshDataDescriptor,
  type MeshIndexFormat,
  type PlaneGeometryOptions,
  type UvSphereGeometryOptions,
} from '@kyxos/render-geometry';
export {
  composeTrsMat4,
  createAabb,
  createQuaternion,
  createVec3,
  identityMat4,
  identityQuaternion,
  multiplyMat4,
  quaternionFromAxisAngle,
  type Aabb,
  type BoundingSphere,
  type Frustum,
  type Mat4,
  type Plane,
  type Quaternion,
  type Vec3,
} from '@kyxos/render-math';
export {
  MATERIAL_TEXTURE_SEMANTICS,
  createLinearRgb,
  createLinearRgba,
  createMaterialFeatureKey,
  createMaterialTextureBinding,
  createMaterialTextureReference,
  createUvTransform,
  linearChannelToSrgb,
  linearToSrgbRgb,
  linearToSrgbRgba,
  materialTextureBindingKey,
  materialTextureSemanticInfo,
  srgbChannelToLinear,
  srgbToLinearRgb,
  srgbToLinearRgba,
  type MaterialFeatureSet,
  type MaterialFeatureValue,
  type MaterialTextureBinding,
  type MaterialTextureBindingDescriptor,
  type MaterialTextureReference,
  type MaterialTextureReferenceDescriptor,
  type MaterialTextureSemantic,
  type MaterialTextureSemanticInfo,
  type RgbColor as LinearRgbColor,
  type RgbaColor as LinearRgbaColor,
  type TextureChannelSelection,
  type TextureTransferFunction,
  type UvTransform,
  type UvTransformDescriptor,
  type Vec2,
} from '@kyxos/render-material-core';
export {
  PBR_TEXTURE_SLOTS,
  PbrMaterial,
  createPbrMaterialFeatureKey,
  type PbrAlphaMode,
  type PbrMaterialChangeEvent,
  type PbrMaterialChangeField,
  type PbrMaterialDescriptor,
  type PbrMaterialEvents,
  type PbrMaterialFeatureDescriptor,
  type PbrMaterialPatch,
  type PbrMaterialSnapshot,
  type PbrTextureBindings,
  type PbrTextureSlot,
} from '@kyxos/render-material-pbr';
export type {
  AssetDecoder,
  BasicGeometryPrimitive,
  MaterialExtension,
  PackPbrObjectUniformsOptions,
  PbrDirectionalLight,
  PbrDirectionalLightDescriptor,
  PbrMaterialLibraryChangeEvent,
  PbrMaterialLibraryChangeKind,
  PbrMaterialLibraryDiagnostics,
  PbrMaterialLibraryEvents,
  PbrMaterialLibraryOptions,
  PbrRenderFeatureDiagnostics,
  PbrRenderFeatureOptions,
  PreviewPreset,
  RenderFeature,
  RendererDiagnostics,
  RendererEvents,
  RendererLifecycleState,
  SceneRenderFeatureDiagnostics,
  SceneRenderFeatureOptions,
} from '@kyxos/render-renderer';
export {
  PBR_OBJECT_UNIFORM_LAYOUT,
  PBR_RENDER_FEATURE_ID,
  KyxosRenderer,
  PbrMaterialLibrary,
  PbrRenderFeature,
  SceneRenderFeature,
  createPbrDirectionalLight,
  packPbrObjectUniforms,
} from '@kyxos/render-renderer';
export {
  Scene,
  type CreateEntityOptions,
  type EntityHandle,
  type LocalTransform,
  type LocalTransformOptions,
  type SceneBoundsOptions,
  type SceneChangeEvent,
  type SceneChangeKind,
  type SceneDiagnostics,
  type SceneEvents,
} from '@kyxos/render-scene';
export {
  MeshRendererStore,
  VisibilitySystem,
  type AlphaMode,
  type BuildRenderQueuesOptions,
  type MeshRendererComponent,
  type MeshRendererDescriptor,
  type MeshRendererStoreChangeEvent,
  type MeshRendererStoreChangeKind,
  type MeshRendererStoreEvents,
  type RenderItem,
  type RenderQueues,
  type RgbaColor,
  type VisibilityDiagnostics,
} from '@kyxos/render-visibility';
export { createBrowserFrameDriver } from './browser-frame-driver.js';
export type { KyxosCanvasRendererOptions } from './canvas-renderer.js';
export { KyxosCanvasRenderer } from './canvas-renderer.js';
export type { CreateKyxosInjectedRendererOptions } from './create-renderer-from-backend.js';
export { createKyxosRendererFromBackend } from './create-renderer-from-backend.js';
export type {
  CreateKyxosCanvasRendererOptions,
  CreateKyxosRendererOptions,
  KyxosBackendSelection,
} from './create-renderer.js';
export { createKyxosRenderer } from './create-renderer.js';
export type { CreateKyxosSceneRendererOptions } from './create-scene-renderer.js';
export { createKyxosSceneRenderer } from './create-scene-renderer.js';
export type {
  KyxosSceneCanvasRendererOptions,
  KyxosSceneRendererDiagnostics,
} from './scene-canvas-renderer.js';
export { KyxosSceneCanvasRenderer } from './scene-canvas-renderer.js';
