/** Stable package identity for diagnostics and boundary tests. */
export const SDK_PACKAGE_NAME = '@kyxos/render-sdk' as const;

export type {
  BackendBindGroupDescriptor,
  BackendBindGroupResource,
  BackendBindGroupHandle,
  BackendBufferData,
  BackendBufferDescriptor,
  BackendBufferHandle,
  BackendCapabilityReport,
  BackendClearColor,
  BackendCommandEncoderDescriptor,
  BackendCommandEncoderHandle,
  BackendDrawCommand,
  BackendEvents,
  BackendFrameSubmission,
  BackendLifecycleState,
  BackendLossInfo,
  BackendPipelineHandle,
  BackendRenderPipelineDescriptor,
  BackendRenderPassDescriptor,
  BackendRenderPassStatistics,
  BackendResourceDescriptor,
  BackendResourceHandle,
  BackendResourceKind,
  BackendResourceStatistics,
  BackendSamplerDescriptor,
  BackendSamplerHandle,
  BackendShaderCompilationInfo,
  BackendShaderModuleDescriptor,
  BackendShaderModuleHandle,
  BackendSurfaceDescriptor,
  BackendSurfaceHandle,
  BackendSurfaceInfo,
  BackendSurfaceResize,
  BackendSurfaceSize,
  BackendSurfaceTarget,
  BackendTextureDescriptor,
  BackendTextureData,
  BackendTextureHandle,
  BackendTextureViewDescriptor,
  BackendTextureViewDimension,
  BackendTextureWriteDescriptor,
  BackendType,
  GraphicsBackend,
} from '@kyxos/render-backend-api';
export { BACKEND_RESOURCE_KINDS, createBackendCapabilityReport } from '@kyxos/render-backend-api';
export {
  DEFAULT_TEMPORAL_HISTORY_RESET_FLAGS,
  FRAME_ACTIVITIES,
  TemporalFrameScheduler,
  type DirtyFlag,
  type FrameActivity,
  type FrameRequestDriver,
  type FrameSchedulerController,
  type FrameSchedulerDiagnostics,
  type RenderMode,
  type ScheduledFrame,
  type TemporalFrameMetadata,
  type TemporalFrameSchedulerOptions,
  type TemporalFrameSchedulerState,
  type TemporalScheduledFrame,
} from '@kyxos/render-frame-scheduler';
export {
  OrbitController,
  PerspectiveCamera,
  frameScene,
  type CameraChangeEvent,
  type CameraChangeKind,
  type CameraDiagnostics,
  type CameraEvents,
  type CameraFitOptions,
  type CameraFitResult,
  type CameraPerspectiveOptions,
  type CameraPoseOptions,
  type FrameSceneOptions,
  type OrbitControllerOptions,
  type OrbitState,
  type PerspectiveCameraOptions,
} from '@kyxos/render-camera';
export {
  createCubeGeometry,
  createMeshData,
  createPlaneGeometry,
  createUvSphereGeometry,
  generateMeshTangents,
  type CubeGeometryOptions,
  type MeshData,
  type MeshDataDescriptor,
  type MeshIndexFormat,
  type PlaneGeometryOptions,
  type UvSphereGeometryOptions,
} from '@kyxos/render-geometry';
export {
  ENVIRONMENT_CUBE_FACES,
  ENVIRONMENT_PACKAGE_NAME,
  EnvironmentLibrary,
  EnvironmentSource,
  encodeFloat16,
  float16BitsToFloat32,
  float32ToFloat16Bits,
  type EnvironmentBrdfLutDescriptor,
  type EnvironmentCubeFace,
  type EnvironmentCubeFaceData,
  type EnvironmentCubeLevelDescriptor,
  type EnvironmentDiffuseIrradianceDescriptor,
  type EnvironmentFloatData,
  type EnvironmentLibraryChangeEvent,
  type EnvironmentLibraryDiagnostics,
  type EnvironmentLibraryEvents,
  type EnvironmentReference,
  type EnvironmentSourceDescriptor,
  type EnvironmentSourceDiagnostics,
  type EnvironmentSpecularPrefilterDescriptor,
} from '@kyxos/render-environment';
export {
  composeTrsMat4,
  createAabb,
  createQuaternion,
  createVec3,
  identityMat4,
  identityQuaternion,
  multiplyMat4,
  quaternionFromAxisAngle,
  type Aabb,
  type BoundingSphere,
  type Frustum,
  type Mat4,
  type Plane,
  type Quaternion,
  type Vec3,
} from '@kyxos/render-math';
export {
  MATERIAL_TEXTURE_SEMANTICS,
  createLinearRgb,
  createLinearRgba,
  createMaterialFeatureKey,
  createMaterialTextureBinding,
  createMaterialTextureReference,
  createUvTransform,
  linearChannelToSrgb,
  linearToSrgbRgb,
  linearToSrgbRgba,
  materialTextureBindingKey,
  materialTextureSemanticInfo,
  srgbChannelToLinear,
  srgbToLinearRgb,
  srgbToLinearRgba,
  type MaterialFeatureSet,
  type MaterialFeatureValue,
  type MaterialTextureBinding,
  type MaterialTextureBindingDescriptor,
  type MaterialTextureReference,
  type MaterialTextureReferenceDescriptor,
  type MaterialTextureSemantic,
  type MaterialTextureSemanticInfo,
  type RgbColor as LinearRgbColor,
  type RgbaColor as LinearRgbaColor,
  type TextureChannelSelection,
  type TextureTransferFunction,
  type UvTransform,
  type UvTransformDescriptor,
  type Vec2,
} from '@kyxos/render-material-core';
export {
  IBL_MAX_REFERENCE_SAMPLE_COUNT,
  IBL_REFERENCE_INPUT,
  IBL_REFERENCE_SAMPLE_COUNT,
  PBR_EXPOSURE_EV_RANGE,
  PBR_TEXTURE_SLOTS,
  PBR_TONE_MAPPING_MODES,
  PbrMaterial,
  convolveDiffuseIrradiance,
  createPbrMaterialFeatureKey,
  evaluateDeterministicIblReference,
  evaluatePbrOutputTransform,
  evaluateSplitSumIbl,
  hammersley2d,
  integrateGgxBrdfLut,
  khronosPbrNeutralToneMap,
  createPbrOutputTransform,
  prefilterGgxSpecular,
  radicalInverseVdc,
  sampleDeterministicIblEnvironment,
  type BrdfLutReference,
  type DeterministicIblReference,
  type DiffuseIrradianceReference,
  type GgxSpecularPrefilterReference,
  type IblEnvironmentSampler,
  type IblVec2,
  type IblVec3,
  type PbrAlphaMode,
  type PbrMaterialChangeEvent,
  type PbrMaterialChangeField,
  type PbrMaterialDescriptor,
  type PbrMaterialEvents,
  type PbrMaterialFeatureDescriptor,
  type PbrMaterialPatch,
  type PbrMaterialSnapshot,
  type PbrOutputTransform,
  type PbrOutputTransformDescriptor,
  type PbrOutputTransformResult,
  type PbrToneMappingMode,
  type PbrTextureBindings,
  type PbrTextureSlot,
  type SplitSumIblInput,
  type SplitSumIblResult,
} from '@kyxos/render-material-pbr';
export {
  TEMPORAL_HISTORY_INVALIDATION_REASONS,
  TEMPORAL_HISTORY_KINDS,
  TEMPORAL_HISTORY_SIGNATURE_FIELDS,
  TEMPORAL_PACKAGE_NAME,
  TEMPORAL_SAMPLE_LIMIT,
  TemporalConvergenceTracker,
  TemporalHistory,
  createTemporalHistorySignature,
  temporalHistorySignaturesEqual,
  type TemporalConvergenceOptions,
  type TemporalConvergenceReason,
  type TemporalConvergenceSnapshot,
  type TemporalHistoryInvalidationReason,
  type TemporalHistoryKind,
  type TemporalHistoryOptions,
  type TemporalHistorySignature,
  type TemporalHistorySignatureDescriptor,
  type TemporalHistorySignatureField,
  type TemporalHistorySnapshot,
} from '@kyxos/render-temporal';
export type {
  AssetDecoder,
  BasicGeometryPrimitive,
  EnvironmentGpuCacheDiagnostics,
  EnvironmentGpuResources,
  MaterialExtension,
  PackPbrObjectUniformsOptions,
  PbrDirectionalLight,
  PbrDirectionalLightDescriptor,
  PbrEnvironmentDescriptor,
  PbrEnvironmentState,
  PbrEnvironmentUniforms,
  PbrMaterialLibraryChangeEvent,
  PbrMaterialLibraryChangeKind,
  PbrMaterialLibraryDiagnostics,
  PbrMaterialLibraryEvents,
  PbrMaterialLibraryOptions,
  PbrNormalYDirection,
  PbrRenderFeatureDiagnostics,
  PbrRenderFeatureOptions,
  PbrTextureLibraryChangeEvent,
  PbrTextureLibraryDiagnostics,
  PbrTextureLibraryEvents,
  PbrTextureSourceDescriptor,
  PreviewPreset,
  RenderFeature,
  RendererDiagnostics,
  RendererEvents,
  RendererLifecycleState,
  SceneRenderFeatureDiagnostics,
  SceneRenderFeatureOptions,
} from '@kyxos/render-renderer';
export {
  PBR_OBJECT_UNIFORM_LAYOUT,
  PBR_RENDER_FEATURE_ID,
  EnvironmentGpuCache,
  EnvironmentGpuLease,
  KyxosRenderer,
  PbrMaterialLibrary,
  PbrRenderFeature,
  PbrTextureLibrary,
  PbrTextureSource,
  SceneRenderFeature,
  createPbrDirectionalLight,
  packPbrObjectUniforms,
} from '@kyxos/render-renderer';
export {
  Scene,
  type CreateEntityOptions,
  type EntityHandle,
  type LocalTransform,
  type LocalTransformOptions,
  type SceneBoundsOptions,
  type SceneChangeEvent,
  type SceneChangeKind,
  type SceneDiagnostics,
  type SceneEvents,
} from '@kyxos/render-scene';
export {
  MeshRendererStore,
  VisibilitySystem,
  type AlphaMode,
  type BuildRenderQueuesOptions,
  type MeshRendererComponent,
  type MeshRendererDescriptor,
  type MeshRendererStoreChangeEvent,
  type MeshRendererStoreChangeKind,
  type MeshRendererStoreEvents,
  type RenderItem,
  type RenderQueues,
  type RgbaColor,
  type VisibilityDiagnostics,
} from '@kyxos/render-visibility';
export { createBrowserFrameDriver } from './browser-frame-driver.js';
export type { KyxosCanvasRendererOptions } from './canvas-renderer.js';
export { KyxosCanvasRenderer } from './canvas-renderer.js';
export type { CreateKyxosInjectedRendererOptions } from './create-renderer-from-backend.js';
export { createKyxosRendererFromBackend } from './create-renderer-from-backend.js';
export type {
  CreateKyxosCanvasRendererOptions,
  CreateKyxosRendererOptions,
  KyxosBackendSelection,
} from './create-renderer.js';
export { createKyxosRenderer } from './create-renderer.js';
export type { CreateKyxosPbrRendererOptions } from './create-pbr-renderer.js';
export { createKyxosPbrRenderer } from './create-pbr-renderer.js';
export type { CreateKyxosSceneRendererOptions } from './create-scene-renderer.js';
export { createKyxosSceneRenderer } from './create-scene-renderer.js';
export type {
  KyxosSceneCanvasRendererOptions,
  KyxosSceneRendererDiagnostics,
} from './scene-canvas-renderer.js';
export { KyxosSceneCanvasRenderer } from './scene-canvas-renderer.js';
export type {
  KyxosPbrCanvasRendererOptions,
  KyxosPbrRendererDiagnostics,
} from './pbr-canvas-renderer.js';
export { KyxosPbrCanvasRenderer } from './pbr-canvas-renderer.js';
