/** Stable package identity for diagnostics and boundary tests. */
export const BACKEND_API_PACKAGE_NAME = '@kyxos/render-backend-api' as const;

export type {
  BackendBufferData,
  BackendBindGroupBinding,
  BackendClearColor,
  BackendDrawCommand,
  BackendFrameSubmission,
  BackendIndexBufferBinding,
  BackendIndexFormat,
  BackendDepthAttachment,
  BackendRenderPassDescriptor,
  BackendRenderPassStatistics,
  BackendVertexBufferBinding,
} from './commands.js';

export type {
  BackendEvents,
  BackendLifecycleState,
  BackendLossInfo,
  BackendStateChange,
  GraphicsBackend,
} from './backend.js';
export type {
  BackendCapabilityReport,
  BackendCapabilityReportOptions,
  BackendFeature,
  BackendLimits,
  BackendType,
} from './capabilities.js';
export { BACKEND_FEATURES, createBackendCapabilityReport } from './capabilities.js';
export type {
  BackendAddressMode,
  BackendBindGroupBufferBinding,
  BackendBindGroupDescriptor,
  BackendBindGroupEntry,
  BackendBindGroupHandle,
  BackendBindGroupResource,
  BackendBindGroupSamplerBinding,
  BackendBindGroupTextureBinding,
  BackendBlendComponent,
  BackendBlendFactor,
  BackendBlendOperation,
  BackendBlendState,
  BackendBufferDescriptor,
  BackendBufferHandle,
  BackendBufferUsage,
  BackendColorTargetDescriptor,
  BackendCompareFunction,
  BackendCommandEncoderDescriptor,
  BackendCommandEncoderHandle,
  BackendCullMode,
  BackendDepthStencilState,
  BackendFilterMode,
  BackendFragmentStageDescriptor,
  BackendFrontFace,
  BackendMipmapFilterMode,
  BackendPipelineHandle,
  BackendPrimitiveState,
  BackendPrimitiveTopology,
  BackendRenderPipelineDescriptor,
  BackendResourceDescriptor,
  BackendResourceHandle,
  BackendResourceHandleKind,
  BackendResourceKind,
  BackendResourceKindStatistics,
  BackendResourceStatistics,
  BackendSamplerDescriptor,
  BackendSamplerHandle,
  BackendShaderCompilationInfo,
  BackendShaderCompilationMessage,
  BackendShaderMessageType,
  BackendShaderModuleDescriptor,
  BackendShaderModuleHandle,
  BackendTextureDescriptor,
  BackendTextureData,
  BackendTextureFormat,
  BackendTextureHandle,
  BackendTextureOrigin,
  BackendTextureSize,
  BackendTextureUsage,
  BackendTextureWriteDescriptor,
  BackendVertexAttribute,
  BackendVertexBufferLayout,
  BackendVertexFormat,
  BackendVertexStageDescriptor,
  BackendVertexStepMode,
} from './resources.js';
export {
  BACKEND_BUFFER_USAGES,
  BACKEND_RESOURCE_KINDS,
  BACKEND_TEXTURE_USAGES,
  backendResourceHandleKind,
  isBackendResourceHandle,
} from './resources.js';
export type {
  BackendSurfaceAlphaMode,
  BackendSurfaceColorSpace,
  BackendSurfaceDescriptor,
  BackendSurfaceFormat,
  BackendSurfaceHandle,
  BackendSurfaceInfo,
  BackendSurfaceResize,
  BackendSurfaceSize,
  BackendSurfaceTarget,
} from './surface.js';
export { normalizeBackendSurfaceSize } from './surface.js';
